name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1


    - name: Debug
      run: |
        pwd
        echo "HOME: ${HOME}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        echo "GOPATH: ${GOPATH}"
        echo "GOROOT: ${GOROOT}"
        mkdir -p ${GOPATH}/{bin,pkg,src}
      env:
        GOPATH: /home/runner/work/immortal/go

    - name: Get dependencies
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
      env:
        GOPATH: /home/runner/work/immortal/go

    - name: Build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go build -o immortal cmd/immortal/main.go
        go build -o immortalctl cmd/immortalctl/main.go
        go build -o immortaldir cmd/immortaldir/main.go
        go test -race -v
      env:
        GOPATH: /home/runner/work/immortal/go
